### PR TITLE
chore: pick prs overwritten

### PR DESCRIPTION
**Pull request by Jack-Works**
pick back #972 and #1001 which seems like accidentally overwritten by #985 cc @guanbinrui 
fw-0000

### CODE REVIEW

**Comment by guanbinrui** [comment]
As @UncleBill reported, this patch led to OOM.

**Comment by Jack-Works** [comment]
can you give more details? cc @UncleBill

**Comment by swkatmask** [comment]
> can you give more details? cc @UncleBill

Sorry, I can't. It just seems that the CI crash due to OOM more often after this patch.

**Review by guanbinrui — APPROVED** [review]

**Comment by Jack-Works** [comment]
> can you give more details? cc @UncleBill

I added this:

`export NODE_OPTIONS=--max_old_space_size=4098`, if that's not enough, maybe it can even bigger

**Pull request closed without merging**
